spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.DriverSpy
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create

logging:
  level:
    jdbc: error
    jdbc.sqltiming: info